'use client'

import dynamic from 'next/dynamic'
import './globals.css'
const DynamicAccountModel = dynamic(() => import(/* webpackChunkName: "AccountModel" */'./Components/AccountModel/AccountModel'))
// import AccountModel from './Components/AccountModel/AccountModel'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        {children}
        <DynamicAccountModel/>
      </body>
    </html>
  )
}

export default RootLayout
